replicaCount: 1

image:
  repository: sultech/sultech-landing
  tag: "1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
