pages:
  image: alpine:latest

  before_script:
    - apk add --no-cache curl tar gzip bash git
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  script:
    - helm package techno
    - mv *.tgz public/
    - helm repo index public/ --url https://sultechno.github.io/helm-chart

  artifacts:
    paths:
      - public

  only:
    - main
